### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by yoyo-gong** [CSC207-2023Y-UofT/course-project-tnt#16]
Write tests for the features.

**Comment by kimmari1** [comment]
Test classes cover user sign in/registration, task list, timer and prompts as required. Test coverage covers all the possible cases a user might run into. Javadoc is still required for certain classes.

**Comment by yoyo-gong** [comment]
The testers for all the issues are done.

**Comment by peterjangml** [comment]
Yay
