### ISSUE TITLE
[Feature 1b] Prompt for 'Continue' and 'Exit' after each break timer ends

### ISSUE THREAD

**Issue by JJ-Han** [CSC207-2023Y-UofT/course-project-tnt#6]
After break timer ends, a user is able to select continue or exit.
[continue] work timer starts
[exit] back to homepage

**Comment by peterjangml** [comment]
JJ-Han has left the team. Therefore, this issue has been closed for restructuring to [Feature 1] https://github.com/CSC207-2023Y-UofT/course-project-tnt/issues/8
