### ISSUE TITLE
[Feature 1] HomePageUI and prompts

### ISSUE THREAD

**Issue by peterjangml** [CSC207-2023Y-UofT/course-project-tnt#8]
As a user wanting to use the pomodoro technique, I want to access an user interface, and receive a prompt in the beginning (pop-up) that asks which task I am working on.

**Comment by peterjangml** [comment]
The HomePageUI (using Android Fragments) and Prompt (from abstract, sub-classes, and calls throughout the app) have been comprehensively developed with complete functionality without any issues.

**Comment by kimmari1** [comment]
Homepage shows the task list and timer as expected, and the prompts show up at the correct times.
